-- c00lcrafter GUI for Dhairya's game only -- Place this inside a LocalScript under StarterGui > ScreenGui

local Players = game:GetService("Players") local player = Players.LocalPlayer local mouse = player:GetMouse()
local screenGui = Instance.new("ScreenGui") screenGui.Name = "c00lcrafterGUI" screenGui.Parent = player:WaitForChild("PlayerGui")
local mainFrame = Instance.new("Frame") mainFrame.Size = UDim2.new(0, 400, 0, 300) mainFrame.Position = UDim2.new(0.3, 0, 0.3, 0) mainFrame.BackgroundColor3 = Color3.fromRGB(30, 30, 30) mainFrame.BorderSizePixel = 4 mainFrame.BorderColor3 = Color3.fromRGB(255, 0, 0) mainFrame.Parent = screenGui
local title = Instance.new("TextLabel") title.Text = "c00lcrafter GUI" title.Font = Enum.Font.SciFi title.TextSize = 24 title.Size = UDim2.new(1, 0, 0, 40) title.BackgroundTransparency = 1 title.TextColor3 = Color3.new(1, 1, 1) title.Parent = mainFrame
 local pages = {} for i = 1, 2 do local page = Instance.new("Frame") page.Size = UDim2.new(1, 0, 1, -40) page.Position = UDim2.new(0, 0, 0, 40) page.BackgroundTransparency = 1 page.Visible = i == 1 page.Name = "Page"..i page.Parent = mainFrame table.insert(pages, page) end
 creator local function createButton(parent, text, position, callback) local button = Instance.new("TextButton") button.Size = UDim2.new(0, 120, 0, 30) button.Position = position button.Text = text button.Font = Enum.Font.SourceSansBold button.TextSize = 18 button.BackgroundColor3 = Color3.fromRGB(100, 0, 0) button.TextColor3 = Color3.new(1,1,1) button.Parent = parent button.MouseButton1Click:Connect(callback) end Page 1 buttons createButton(pages[1], "Fly", UDim2.new(0, 10, 0, 10), function() print("Fly activated") end) createButton(pages[1], "Commitoof", UDim2.new(0, 10, 0, 50), function() player.Character:BreakJoints() end) createButton(pages[1], "Speed", UDim2.new(0, 10, 0, 90), function() player.Character.Humanoid.WalkSpeed = 100 end) createButton(pages[1], "JumpPower", UDim2.new(0, 10, 0, 130), function() player.Character.Humanoid.JumpPower = 150 end) createButton(pages[1], "Invisible", UDim2.new(0, 10, 0, 170), function() for _,v in pairs(player.Character:GetDescendants()) do if v:IsA("BasePart") then v.Transparency = 1 end end end) createButton(pages[1], "GodMode", UDim2.new(0, 10, 0, 210), function() player.Character.Humanoid.MaxHealth = math.huge player.Character.Humanoid.Health = math.huge en Page 2 buttons createButton(pages[2], "Orbit Parts", UDim2.new(0, 10, 0, 10), function() print("Orbit effect coming soon") end) createButton(pages[2], "Blackhole", UDim2.new(0, 10, 0, 50), function() print("Blackhole sucking parts...") end) createButton(pages[2], "View /player/", UDim2.new(0, 10, 0, 90), function() print("Viewing player...") end) createButton(pages[2], "ChatLogs", UDim2.new(0, 10, 0, 130), function() print("Chat logging started") end) createButton(pages[2], "Day", UDim2.new(0, 10, 0, 170), function() game.Lighting.TimeOfDay = "14:00:00" end) createButton(pages[2], "Night", UDim2.new(0, 10, 0, 210), function() game.Lighting.TimeOfDay = "00:00:00" end)
Minimise & Close Buttons createButton(pages[2], "Minimise GUI", UDim2.new(0.6, 0, 0, 250), function() mainFrame.Visible = false end)
local closeButton = Instance.new("TextButton") closeButton.Text = "X" closeButton.Size = UDim2.new(0, 30, 0, 30) closeButton.Position = UDim2.new(1, -35, 0, 5) closeButton.TextColor3 = Color3.new(1,0,0) closeButton.BackgroundColor3 = Color3.new(0,0,0) closeButton.Parent = mainFrame closeButton.MouseButton1Click:Connect(function() screenGui:Destroy() end)
Page Switch Arrows local currentPage = 1 local function switchPage(toPage) for i, p in ipairs(pages) do p.Visible = (i == toPage) end currentPage = toPage end
local nextBtn = Instance.new("TextButton") nextBtn.Text = ">" nextBtn.Size = UDim2.new(0, 30, 0, 30) nextBtn.Position = UDim2.new(1, -35, 1, -35) nextBtn.Parent = mainFrame nextBtn.MouseButton1Click:Connect(function() switchPage(2) end)
local prevBtn = Instance.new("TextButton") prevBtn.Text = "<" prevBtn.Size = UDim2.new(0, 30, 0, 30) prevBtn.Position = UDim2.new(0, 5, 1, -35) prevBtn.Parent = mainFrame prevBtn.MouseButton1Click:Connect(function() switchPage(1) end)
print("c00lcrafter GUI loaded!")
￼Enter
